### ISSUE TITLE
Conneting to server with self signed certificate

### ISSUE THREAD

**Issue by jerzydubin** [meonkeys/ow#2]
Hello,
i tried to run it over my local installation where i used self signed certificate :
`jurek@debian:~/programy/ow$ ./ow dir-album "/Lokalny/OEF/OEF2013"
⛔ PROPFIND request failed: HTTPSConnectionPool(host='192.168.1.9', port=443): Max retries exceeded with url: //remote.php/dav/files/jurek//Lokalny/OEF/OEF2013 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))`

**Comment by jerzydubin** [comment]
I added `verify=False` flag in each request method and it is working.

**Comment by meonkeys** [comment]
Sounds good. I'll accept a patch if you or anyone wants to add something like curl's `-k` / `--insecure` to skip cert checking.
